### ISSUE TITLE
REQUEST for camera entities

### ISSUE THREAD

**Issue by pergolafabio** [unixorn/ha-mqtt-discoverable#109]
**Is your feature request related to a problem? Please describe.**
Hi , it it possible to create also support for camera entities, to upload maybe jpg pictures files?

thnx in advance

**Comment by pergolafabio** [comment]
And maybe also for the Mqtt image platform?

https://www.home-assistant.io/integrations/image.mqtt/

**Comment by Gifford47** [comment]
That would be awesome! @unixorn can you give me a hint how to start implementing?

**Comment by unixorn** [comment]
Sorry it's taken so long to respond, I've had a hectic few weeks.

I don't currently have any cameras connected to my HA to do any testing.

After looking at the image.mqtt link upthread, I think adding `payload_available`, `payload_not_available` and `url_topic` topics to an object would do it, but I can't test.

RN I can't really do much in the way of implementing features I'm not using because my life's a bit hectic lately. I am happy to merge in new code - I make a point to check at least every weekend for PRs.

**Comment by Gifford47** [comment]
Thanks for this awesome lib! I've added camera, image and selection discovery in #264. I've tested it manually on my host machine, so I've not added any tests to this repo yet. Do you merge it also without the tests?

**Comment by unixorn** [comment]
I'd prefer tests but you can add them in another PR
